### ISSUE TITLE
Shell tab completion

### ISSUE THREAD

**Issue by ineffyble** [batect/batect#116]
It would be amazing if batect supported bash/shell autocompletion (e.g. so I can type `./batect bu`, hit <tab>, and have it autocomplete to `./batect build`).

**Comment by charleskorn** [comment]
Hey @ineffyble, thanks for the feedback. I completely agree - this would be awesome, and it's been on the roadmap for a while. 

I was playing around with getting this working for Fish a few weeks ago and it looks like it wouldn't be too much work for other shells either. Once I've finished adding support for Windows, I'll look into this further.

**Comment by binkley** [comment]
I've noticed tooling has definitely been moving in this direction.  Perhaps one of the implementation approaches might make sense for `batect`?

- `jenv init -`
- `golangci-lint completion bash`
- `rustup completions bash`

Since `batect` has "reflection" for tasks (ie, `-T` works), it might be straight forward.

**Comment by charleskorn** [comment]
This is definitely still something I want to do, I've just had more urgent things crop up sadly. I'm always open to PRs if you're interested in contributing one, otherwise, watch this space :)

**Comment by binkley** [comment]
@charleskorn Do you have a preferred strawman command line syntax?

**Comment by charleskorn** [comment]
I've been thinking about it, but I haven't decided on anything. Here are some of the things going through my mind:

One of the constraints we have is that `batect` isn't installed globally (unlike the examples you posted above), so a user couldn't just put `source <(batect completion bash)` in their `.bashrc`, as they'd have to point to a particular project's `batect` wrapper script. 

The other constraint is that different projects may be using different versions of batect, so we have to at least gracefully handle that (and showing the relevant options for different versions would be a nice to have on top of that - I know @ineffyble's original comment was just about tasks, but at some point we'll want to include CLI options like `--output` in the completions as well).

These are some of the ideas I've had, I'm interested to hear others as well:

* We have a `./batect --install-completions bash` which would put the completion script for that version into `/etc/bash_completion.d` or `~/.local/share/bash-completion` or `~/.bash_completion` (whichever one makes the most sense). 

  To ensure this stays up-to-date (or even gets installed in the first place), we could show a prompt similar to the update prompt to nudge users to run `./batect --install-completions bash` when we detect the file is out-of-date or not installed.

  Pros: all within the existing tooling, good discoverability (can prompt user to install it and update it). Cons: user has to run a special command to update the completion script every time it changes.

* Similar to above, but the distribution mechanism is the OS package manager (eg. Homebrew, APT).

  Pros: updates are handled for us automatically, can ensure any dependencies (eg. `bash-completion`) are installed correctly. Cons: have to set up many distribution channels to reach all users, reliant on users keeping that up-to-date.

* Instead of a completions script that contains all CLI flags and logic to get tasks etc., we distribute (via either of the above mechanisms) a very simple completion script that delegates to the project's `batect` wrapper script to do completions. 

  Pros: less frequent updating of completion script required, guaranteed to show correct options for project's version of batect. Cons: would expect this to be slower as we'd have to start a JVM every time the user tries to complete something.

**Comment by charleskorn** [comment]
https://github.com/batect/batect/pull/649 may be of interest to you - it is an RFC for how this could actually be implemented.

**Comment by ineffyble** [comment]
One thing to be careful of is breaking environments when files move.

Serverless Framework uses a Node package called `tabtab` to automatically add bash completions by adding a line to the user's `.bashrc` (or similar). This happens automatically when you run `npm install` (without any option to stop this happening), and the line in the `.bashrc` (or similar) points at a file in the relevant `node_modules` folder.

Which means that if you delete the project or move it, suddenly the `.bashrc` exits half-way through when it hits an error. Which caused all sorts of problems for me in the past.

**Comment by charleskorn** [comment]
Thanks for the feedback @ineffyble. My plan is to have only one globally-installed script per shell, and use mechanisms like Fish's `/usr/local/share/fish/vendor_completions.d` and Homebrew's `/usr/local/etc/bash_completion.d` for Bash - these simply load whatever is present in these directories, so there's no risk of issues with things being moved or uninstalled.

**Comment by charleskorn** [comment]
📢 I've just released [v0.62](https://github.com/batect/batect/releases/tag/0.62.0) which includes shell tab completion support for Fish. I'll add support for other shells (including Bash and zsh) in a future release.

If you have any feedback on this, please feel free to post it here or open a separate issue for bugs.

**Comment by charleskorn** [comment]
📢 I've just released [v0.67](https://github.com/batect/batect/releases/tag/0.67.0) which includes shell tab completion support for Zsh.
 
If you have any feedback on this, please feel free to post it here or open a separate issue for bugs.

**Comment by charleskorn** [comment]
...and this is also now available as a Oh My Zsh plugin if you'd rather not use Homebrew: https://github.com/batect/zsh-completion#with-oh-my-zsh

**Comment by binkley** [comment]
Seeing lots of great stuff in this space.  Any thoughts on timeline for BASH support?

**Comment by charleskorn** [comment]
My current focus is on BuildKit support - once that's out of the way (hopefully soon 🤞), this should be near the top of the list.

**Comment by charleskorn** [comment]
📢 I've just released [v0.73](https://github.com/batect/batect/releases/tag/0.73.0) which includes shell tab completion support for Bash.
 
If you have any feedback on this, please feel free to post it here or open a separate issue for bugs.

I'm considering this feature complete now, given that all of Bash, Fish and Zsh are now supported 🎉  (If there's great interest in PowerShell, I'll consider adding that in the future, but at the moment, telemetry is telling me there aren't a huge number of people out there using Batect from PowerShell. If you're reading this and PowerShell support is important to you, please open a new feature request.)
