### ISSUE TITLE
Improve Batect's output when caching is used

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1331]
### Describe the problem you'd like to solve

I'd like to better be able to debug performance issues with Batect runs, e.g. by better understanding when Batect is able to make use of cached Docker (base) images and / or layers.

For example, even if the base image has already been fully pulled, Batect outputs

```
Pulling eclipse-temurin:11-jdk-jammy...
Pulled eclipse-temurin:11-jdk-jammy.
```

which makes it look from the console as is the whole images has been repulled (when not being able to see timestamps for these two commands in order to calculate the duration).

### Describe the solution you'd like

For the scenario of cached base images, it'd be nice if Batect clearly said something like

```
Using (cached) eclipse-temurin:11-jdk-jammy.
````

And for building layers, it would be nice if there was some final output for how many of how many total layers could be reused from the Docker layer cache.

### Additional context

https://github.com/batect/batect/discussions/1245

**Comment by sschuberth** [comment]
In essence, I'd like to better understand how much time of a Batect run is spent with (implicit) (re-)building of the Docker image vs. running tasks *in* the Docker image. Something like

```
Total time was 7m40s.
Spent 5m30s with the Docker build.
Spent 2m10s with running tasks in Docker.
```

**Comment by charleskorn** [comment]
Thanks for the feedback @sschuberth.

> For the scenario of cached base images, it'd be nice if Batect clearly said something like
> ```
> Using (cached) eclipse-temurin:11-jdk-jammy.
> ```
> And for building layers, it would be nice if there was some final output for how many of how many total layers could be reused from the Docker layer cache.

This is an interesting idea, and shouldn't be too difficult to support.

> In essence, I'd like to better understand how much time of a Batect run is spent with (implicit) (re-)building of the Docker image vs. running tasks in the Docker image. Something like...

This is a little trickier to provide in a way that is meaningful: because Batect starts running containers as soon as their image and dependent containers are ready, the total task time isn't a straightforward sum of the time taken to build all images plus the time taken to run the task command. Perhaps something that visualises the task execution on a timeline would be more helpful? I'm imagining something like a Gradle Build Scan or one of the many similar tools for Bazel. What do you think?

(This information is already available in a structured-ish format in Batect's JSON-formatted logs, so if you're interested in trying to pull something together yourself, you should be able to use that as a starting point.)

**Comment by sschuberth** [comment]
> Perhaps something that visualises the task execution on a timeline would be more helpful? I'm imagining something like a Gradle Build Scan or one of the many similar tools for Bazel. What do you think?

As long as it can easily be used / works nicely with CI builds, something like that would certainly be helpful.

> This information is already available in a structured-ish format in Batect's JSON-formatted logs, so if you're interested in trying to pull something together yourself, you should be able to use that as a starting point.

Interesting. Maybe one could create some Markdown from that JSON, and use it as a [GitHub Action job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/).
