### ISSUE TITLE
Error attaching: configured logging driver does not support reading

### ISSUE THREAD

**Issue by nashvan** [batect/batect#299]
This issue happens when I am trying to run batect (which is going to run a docker) in our Jenkin agent which is a dockerised agent hosted on ecs. I have mounted docker socket into docker in batect.yaml as below:
containers:
  build-env:
    build_directory: dev-infra/build-env
    volumes:
    - local: .
      container: /code
      options: cached
    - /var/run/docker.sock:/var/run/docker.sock 
........

any idea what could cause this issue.

**Comment by charleskorn** [comment]
Hi @nashvan, sorry to hear you're having issues. Just to make sure I understand correctly, is this what you're trying to do:

* You have a Jenkins agent hosted in a Docker container running on ECS
* You're running batect with the configuration above
* You'd like to mount the ECS host's Docker socket into `build-env` 

Is that correct? If so, what would you like to do inside `build-env`?

**Comment by nashvan** [comment]
@charleskorn Thank you very much for your reply. that is exactly true. 
Inside build-env I am trying to run Terraform commands.

**Comment by charleskorn** [comment]
OK, do you have the same issue if you try to run a Docker container on that same agent without batect?

**Comment by nashvan** [comment]
Had to change the logging drive and keep it as default (json-file), and that issue fixed. but now facing a terraform versioning issue which I am not getting that issue if I ran the pipeline without batect. while both dockers are using same terraform version.

**Comment by charleskorn** [comment]
Great to hear the original issue has been fixed. Could you share more details of the error you're seeing with Terraform?

**Comment by nashvan** [comment]
Actually before that, how we can make batect work and read docker daemon's logs from awslog instead of json-file? is this something to do with batect or the docker container that batect runs on top of our jenkins slave "container"?

**Comment by avnab** [comment]
hi @charleskorn .   not being able to use awslogs driver is a bit of a showstopper for teams using jenkins ecs slaves that want/need to capture logs in cloudwatch. 

it appears that the awslogs driver does not support reading, so things like `docker logs <id>` does not work.  i think when batect tries to attach to container output it is failing due to this.   

when the container runs, this is called:
https://github.com/charleskorn/batect/blob/55539d5766895910db9c582bd9a8a6a8a894cebd/app/src/main/kotlin/batect/docker/client/DockerContainersClient.kt#L90

which in turn tries to attach to output stream:
https://github.com/charleskorn/batect/blob/55811a70269374d43a5ea3338f53c3507c3a99e8/app/src/main/kotlin/batect/docker/api/ContainersAPI.kt#L323

Looking at the docs here, the docker api for logs only works for json-file and journald loggers.
https://docs.docker.com/engine/api/v1.20/

and i'm wondering if the attach api has a similar limitation, and perhaps the `log` querystring can be made optional? default is false according to docker api docs above.
https://github.com/charleskorn/batect/blob/55811a70269374d43a5ea3338f53c3507c3a99e8/app/src/main/kotlin/batect/docker/api/ContainersAPI.kt#L331

**Comment by charleskorn** [comment]
Hey @nashvan and @avnab, yep, we can definitely fix this in batect. Looks like the solution would be to explicitly set the log driver for all containers we create to `json-file`. 

This is specified when [the container is created](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate) in the `HostConfig.LogConfig.Type` property, so we'd need to add that to `DockerContainerCreationRequest.toJson()`: https://github.com/charleskorn/batect/blob/55539d5766895910db9c582bd9a8a6a8a894cebd/app/src/main/kotlin/batect/docker/DockerContainerCreationRequest.kt#L46

It seems like you're quite comfortable digging through the code - would you be keen to submit a PR? Otherwise happy to fix it myself :)

**Comment by avnab** [comment]
Hi @charleskorn, i've built a version with the logs qs set to false to test tomorrow.   wrt forcing the logconfig to use json-file, i don't think that is an approach we can use, as we need to ensure that container logs are sent to cloudwatch from these containers for policy reasons.   we'll do a bit of testing and then perhaps we can chat about options to deal with this in a PR.

**Comment by wyvern8** [comment]
switching gh accounts.. btw great work on this tool - very useful.

**Comment by wyvern8** [comment]
another thought @charleskorn - if we do use json-file for launched containers, the ecs slave would log the stdout and stderr of the step containers via awslogs - correct?  that might be accepatable if so. wiil test that.

**Comment by wyvern8** [comment]
Draft PR for testing.  https://github.com/charleskorn/batect/pull/304
