### ISSUE TITLE
How to clean up old versions of batect jar?

### ISSUE THREAD

**Issue by binkley** [batect/batect#475]
Poking around `$HOME` I noticed `.batect`, and naturally ran `find .batect -type f`.  I see it's a cache for downloaded Batect jars going back for a while.

Trying the `--clean` flag, I see it cleans up cache mounts (yeah!), however does nothing for the cached jars.

Is there something I'm missing in letting Batect manage cleaning up the cached jars?  I could do this by hand (the layout of `.batect` is clean and sensible), but *would prefer letting Batect manage this*.

----

Aside: I see the `rfcs` docs in the repo.  Nice idea!  I did check here as well.

**Comment by charleskorn** [comment]
It's an interesting idea (especially because I just looked at my local `~/.batect` and it was nearly 1 GB in size 😱).

I'm thinking that, as a first pass, we could add a `./batect --cleanup-downloads` command that would remove anything in `~/.batect/cache` older than the current version. 

A future improvement would be to track the last time a version in the cache was used and automatically delete it if it gets to more than X days without being used.

How does that sound?

**Comment by binkley** [comment]
That sounds sensible.

An enhancement (different story card? :) ) would be that upgrading Batect auto-removes the previous version.

I can see some niggles here: removing a version which in use by another Batect-enabled project.  The worst case there is that the removed version is redownloaded.

**Comment by charleskorn** [comment]
I've added automatic background cleanup of downloaded files that haven't been used in 30 days, and this will be part of the next release.

Thanks for the feedback @binkley!
