### ISSUE TITLE
More concise passing of environment variables

### ISSUE THREAD

**Issue by ineffyble** [batect/batect#68]
Our batect.yml currently has many many lines under `environment` blocks that look like:

```
environment:
    HOSTNAME: $HOSTNAME
```

When you want to pass a host variable through to the container as the same name and value, a more concise format could be helpful. This is something [Docker-Compose](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers) and Buildkite do well.

E.g.:

```
environment:
    - HOSTNAME
```

**Comment by charleskorn** [comment]
Makes sense to me, thanks for the suggestion @ineffyble!

**Comment by nesl247** [comment]
Should I open another issue to have the same support for `build_args`?

**Comment by charleskorn** [comment]
@nesl247 are you asking for the ability to use environment variables in build arg values?

**Comment by nesl247** [comment]
I'm looking for this exact same feature but for build_args. In docker-compose, if you don't pass a value to an `environment` or `build_arg` key, it will get the value from the runtime environment variables if it exists.

This issue is exactly about this, but only `environment` was mentioned, not `build_args`. If you want me to open another issue still I would be happy to do so.

**Comment by charleskorn** [comment]
I'd consider support for environment variables in build args to be a different feature to what's been requested in this issue, so please open a separate issue.

**Comment by charleskorn** [comment]
I'm going to close this as won't fix - the existing syntax, while verbose, is more explicit and means we can use standard YAML maps rather than a list which needs to be parsed.
