### ISSUE TITLE
Get rid of the hypirion.io dependency

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#984]
### Describe the problem you'd like to solve

[hypirion.io](https://github.com/hypirion/com.hypirion.io) seems unmaintained for years and is only hosted on JCenter, which has [set its sails](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). As only its RevivableInputStream seems to be used, maybe it's easy enough to migrate to an alternative.

### Describe the solution you'd like

Ideally, the already used Okio library has similar functionality that could be used.

### Describe alternatives you've considered

Maybe creating an own class based in the RevivableInputStream implementation would be an option.

### Additional context

I was looking at this in the context of migrating Groovy build script to Kotlin.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. 

> Ideally, the already used Okio library has similar functionality that could be used.

Is this something that already exists in Okio? If not, it might be worth raising with them.

**Comment by sschuberth** [comment]
> Is this something that already exists in Okio?

No idea. What exactly *is* the functionality of `RevivableInputStream` you're using? I'm aware of the `kill` and `resurrect` calls, but I have to admit I'm not really grasping the use-case.

**Comment by charleskorn** [comment]
`RevivableInputStream` is used when we're streaming stdin to a container. If the container stops, we need to stop any pending read from stdin without closing stdin (because then we wouldn't be able to use it in any subsequent tasks). This is where `kill` comes in: it aborts the pending read without closing the stream, allowing us to then `resurrect` the stream and continue reading from it in the future.
